name: Create Release

on:
  workflow_run:
    workflows: ['Run Tests on Tag']
    types:
      - completed


jobs:
  release:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get tag name
        id: get-tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "Tag: $TAG"
          echo "::set-output name=tag::$TAG"


      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.get-tag.outputs.tag }}
          release_name: Release ${{ steps.get-tag.outputs.tag }}
          body: |
            This release was created based on the tag **${{ steps.get-tag.outputs.tag }}**.
          draft: false
          prerelease: false