name: Run Tests

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ "3.11" ]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [[ "${{ runner.os }}" == "macOS" ]]; then
          pip install --no-binary :all: numpy==1.22.4
          pip install --no-binary :all: setuptools==57.0.0
          pip install --no-deps -r requirements.txt
        else
          pip install -r requirements.txt
        fi

    - name: Install StatTools
      shell: bash
      run: |
        python setup.py install

    - name: Run tests
      run: |
        pytest tests/
