name: Run Tests

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ "3.11" ]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip setuptools wheel
        if [[ "${{ runner.os }}" == "macOS" ]]; then
          pip install numpy --prefer-binary
          pip install scipy --prefer-binary
          pip install --no-binary :all: -r requirements.txt
        else
          pip install -r requirements.txt
        fi
        pip install pytest

    - name: Install StatTools
      shell: bash
      run: |
        python setup.py install

    - name: Run tests
      run: |
        pytest tests/

  build-wheels:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ "3.11" ]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    needs: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel build

    - name: Build wheels
      run: |
        python -m build --wheel --outdir wheelhouse

    - name: Upload wheels as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: ./wheelhouse/*.whl
