name: Run Tests

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ "3.11" ]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [[ "${{ runner.os }}" == "macOS" ]]; then
          pip install --no-binary :all: numpy
        fi
        pip install pytest
        pip install -r requirements.txt

    - name: Install StatTools
      shell: bash
      run: |
        python setup.py install
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          echo "Adding Python to PATH"
          echo "$(python -c 'import sys; print(sys.executable)')" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        fi

    - name: Run tests
      run: |
        pytest tests/
