name: Test and release

on:
  push:
    tags:
      - 'release-[0-9]*.[0-9]*.[0-9]'

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt

      - name: Install StatTools
        run: |
          python setup.py install

      - name: Run tests
        run: |
          pytest tests/

  deploy:
    runs-on: ubuntu-22.04
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get release name
        id: get-release
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "Tag: $TAG"
          echo "::set-output name=tag::$TAG"

      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get-release.outputs.tag }}
          name: Release ${{ steps.get-release.outputs.tag }}
          draft: false
          prerelease: false
          body: |
            This release was created based on the tag **${{ steps.get-release.outputs.tag }}**.
